
language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-26.0.2
    - android-26
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - extra

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - gradle assemble
